var data={
    Promisify:{
        date:"2016-01-21",
        category:"/article/techs",
        href:"/article/techs/promisify",
        title:"如何在JS中按顺序执行若干个异步函数",
        discription:"利用promise实现按数组顺序同步执行若干个同步或异步函数并返回。",
    },   
    MaxHeightCSS3Transition:{
        date:"2015-11-20",
        category:"/article/techs",
        href:"/article/techs/MaxHeightCSS3Transition",
        title:"通过CSS动画设置max-height实现自适应伸展div动画效果",
        discription:"通过CSS动画设置max-height实现自适应伸展div动画效果",
        css:"MaxHeightCSS3Transition.css",
    },
    EmbracingPromisesInJavaScript:{
        date:"2015-11-07",
        category:"/article/techs",
        href:"/article/techs/EmbracingPromisesInJavaScript",
        title:"在JavaScript中使用Promise",
        discription:"Embracing Promises In JavaScript译文。原作者：Jack Franklin",
    },
    BlackSheep:{
        date:"2015-11-05",
        category:"/article/literature",
        href:"/article/literature/BlackSheep",
        title:"黑羊",
        discription:"我翻译的卡尔维诺短篇小说《黑羊》",
    },
    SmartBookmark:{
        date:"2015-10-20",
        category:"/article/projects",
        href:"https://chrome.google.com/webstore/detail/smartbookmark/anphpbfahagkdljlgeajoooiogcfnoee?hl=zh-CN",
        title:"SmartBookmark",
        discription:"一个智能管理书签的chrome插件",
    },
    Zwei:{
        date:"2015-03-15",
        category:"/article/projects",
        href:"static/projects/Zwei",
        title:"Zwei",
        discription:"Zwei是一个模仿Duet的HTML5小游戏",
    },
    DataTableFilter:{
        date:"2015-03-15",
        category:"/article/projects",
        href:"static/projects/DataTableFilter",
        title:"DataTables筛选器",
        discription:"DataTables筛选器是DataTables的一个插件，可以让DataTables的表格具有像Excel那样的筛选功能",
    },
    jsAlgorithmsDEMO:{
        date:"2015-03-15",
        category:"/article/projects",
        href:"static/projects/jsAlgorithmsDEMO",
        title:" JavaScript算法DEMO",
        discription:"集合了一些JavaScript算法的小DEMOs，学习用",
    },
    jsDesignPatterns:{
        date:"2015-03-15",
        category:"/article/projects",
        href:"static/projects/jsDesignPatterns",
        title:"JavaScript设计模式DEMO",
        discription:"集合了一些JavaScript设计模式的小DEMO，学习用",
    },
}

module.exports=data